ROTORS = {
    "III": "BDFHJLCPRTXVZNYEIWGAKMUSQO", #ROTOR 3
    "II": "AJDKSIRUXBLHWTMCQGZNPYFVOE", # ROTOR 2
    "I": "EKMFLGDQVZNTOWYHXUSPAIBRCJ" # ROTOR 1
}
ROTOR_TURNOVER = {
    "III": 22,
    "II": 5,
    "I": 17
}
REFLECTOR_A = "EJMZALYXVBWFCRQUONTSPIKHGD"
REFLECTOR_B = "YRUHQSLDPXNGOKMIEBFZCWVJAT"
REFLECTOR_C = "FVPJIAOYEDRZXWGCTKUQSBNMHL"
REFLECTOR = REFLECTOR_B