ROTORS = {
    0: "BDFHJLCPRTXVZNYEIWGAKMUSQO", #ROTOR 3
    1: "AJDKSIRUXBLHWTMCQGZNPYFVOE", # ROTOR 2
    2: "EKMFLGDQVZNTOWYHXUSPAIBRCJ" # ROTOR 1
}
REFLECTOR_A = "EJMZALYXVBWFCRQUONTSPIKHGD"
REFLECTOR_B = "YRUHQSLDPXNGOKMIEBFZCWVJAT"
REFLECTOR_C = "FVPJIAOYEDRZXWGCTKUQSBNMHL"
REFLECTOR = REFLECTOR_B