ROTORS = {
    0: "EKMFLGDQVZNTOWYHXUSPAIBRCJ",
    1: "AJDKSIRUXBLHWTMCQGZNPYFVOE",
    2: "BDFHJLCPRTXVZNYEIWGAKMUSQO"
}
REFLECTOR_A = "EJMZALYXVBWFCRQUONTSPIKHGD"
REFLECTOR_B = "YRUHQSLDPXNGOKMIEBFZCWVJAT"
REFLECTOR_C = "FVPJIAOYEDRZXWGCTKUQSBNMHL"
REFLECTOR = REFLECTOR_B